### PR TITLE
Hickle subclasses

### PR DESCRIPTION
**Pull request by 1313e**
This PR adds support for hickling objects that are subinstances of classes that hickle supports.
So, for example, anything that subclasses a `dict` can now be hickled properly as well.
This PR also includes the changes made in #109.
Finally, I have removed all instances where the type of a hickled dataset was saved as a list instead of just a normal string.

As it is required to save a bit more data in the HDF5-file now, previously made hickle-files are not supported.

### CODE REVIEW

**Comment by telegraphic** [comment]
Sounds great, and at first look I like the approach. I'll have a better look this week -- will need to consider legacy support and/or warnings so that users don't panic if their hkl files don't load.

**Comment by 1313e** [comment]
Alright.
You will have to accept #109 first though, as this one used the changes introduced in it.
Although, it literally only modifies the location of the tests.

**Comment by 1313e** [comment]
I thought about implementing it in such a way, that older Hickle files are still supported, but that is a whole lot of extra work.
Especially as I also changed the string types to be saved as a single scalar, instead of a list.

**Comment by 1313e** [comment]
If you want, I can add a simple warning that checks if the file was created with a specific Hickle version or newer, and raises a warning/error if not.
You may want to implement something similar to what I have in PRISM, where I write down a list of version strings that specify what is compatible and what not.

**Comment by 1313e** [comment]
@telegraphic Any updates?

**Comment by 1313e** [comment]
I just realized that with the changes in this PR, an `OrderedDict` would be able to be hickled (as requested in #65), but reading it back in would not go correctly in Python versions earlier than 3.6 (because it would first be transformed to a dict, making the entries have a random position, and then to an ordered one).

I can check if I can actually make sure to try to initialize the object after reading with its actual type first, and fall back to the base type if that does not work.

**Comment by telegraphic** [comment]
Noted, good catch. I'm playing around with your changes atm, think changes are good but still thinking about legacy support. I think a major version bump?

**Comment by 1313e** [comment]
I also just realized that that cannot be fixed easily, as Hickle currently does not save in what order the keys should be sorted.
Therefore, in all Python versions the dict will not be read back in correctly, because HDF5 automatically sorts its keys.

**Comment by 1313e** [comment]
So, what we can do, is try to implement it such that the order in which the dict keys were given, is also saved and try to always initialize the hickled object using its true type first, and only fall back to the base type into true type if the prior fails.

**Comment by 1313e** [comment]
I have an idea, and will work it out over the next few hours.
Keep an eye out for more commits.

**Comment by telegraphic** [comment]
Ah yes, I ran into this with heterogenous lists (e.g. `[1, np.array([1]), '1']`) -- HDF5 datasets are not ordered as such, so extra book-keeping was required. This is why if you open with h5py you'll see internally datasets `data_0`, `data_1` and so on. 

There's a necessary sort in the [_load function on L#594](https://github.com/telegraphic/hickle/blob/master/hickle/hickle.py#L594) to figure out correct order when loading.

In Py3.7 they changed dict so [insertion order is preserved](https://docs.python.org/3.7/whatsnew/3.7.html) -- so yes agreed incompatible change is reasonable

**Comment by 1313e** [comment]
Yeah, but as HDF5 will sort the keys anyways, it does not really matter if dicts preserve their insertion orders or not.

**Comment by telegraphic** [comment]
I just meant that a round-trip dict->hdf5->dict in Py3.7 will not preserve order, as the code currently stands, thus hickle has unexpected behavior in Py 3.7. 

Looks like h5py actually does have a `track_order` http://docs.h5py.org/en/stable/high/group.html#dict-interface-and-links, added late 2017, that might be useful. That probably adds a h5py > 2.8.0 requirement though.

The underlying C API seems to have had capability to track creation order since HDF5 1.8.0 (2009?) - https://portal.hdfgroup.org/display/HDF5/H5P_SET_LINK_CREATION_ORDER

**Comment by 1313e** [comment]
@telegraphic I already solved the problem.
I am not entirely sure what is better, as this implementation will guarantee that it works the way we want.

**Comment by telegraphic** [comment]
Ok, let me know.  Getting rid of the `data_i` thing would be nice. Definitely leaning toward a `4.0` release given the changes are pretty major

**Comment by 1313e** [comment]
I have done a bit of testing, and it seems to work fine.
No idea where in the HDF5-file it actually saves what the original order was (as it still shows the actual items in a group sorted alphabetically, but asking for its keys specifically will indeed return them in the correct order).
If we use that, then the minimum h5py version becomes 2.9.0.

Question: Do you want the `track_order` parameter to be set globally for h5py, making its implementation easier but running the risk somebody else overrides it again; or be provided specifically to every group that is ever created?

**Comment by 1313e** [comment]
WOW!
I have absolutely no clue how I ever missed that one, but I just realized that I never added the `six` requirement to the requirements list.

**Comment by telegraphic** [comment]
Could we put the `h5py.get_config().track_order = True` into the `dump()` method?

**Comment by 1313e** [comment]
> Could we put the `h5py.get_config().track_order = True` into the `dump()` method?

Probably, yeah.

**Comment by 1313e** [comment]
Currently, most things are in place, but I have not figured out yet how to make sure that a `namedtuple` is supported (the annoying thing about them is that there is no way of figuring out that something was made by a named tuple).

**Comment by 1313e** [comment]
After fiddling around for a long time, I realized that it is really hard to get rid of the (seemingly) pointless `data_0` groups/datasets.
They indicate levels of dimensionality, and are required when an object goes deeper than a single level at once (like `[[1]]`).
Theoretically speaking, I could implement it in such a way that it removes the first level every time, but that will require remembering how many levels down the object has already gone without any changes.

**Comment by 1313e** [comment]
> Could we put the `h5py.get_config().track_order = True` into the `dump()` method?

As I have reported in h5py/h5py#1385, using `h5py.get_config().track_order = True` causes some problems.
Until that is fixed, I think we cannot really use it for anything.

**Comment by telegraphic** [comment]
ok, agreed, let's not rely on it! Let me know when this avenue has reached a logical point to stop and merge -- if we're changing the underlying data structures we should make sure we are certain it won't change again (in the foreseeable future at least)

**Comment by 1313e** [comment]
Up to commit `9464a7c` can definitely be merged, although there are a few later commits that I would like to add as well to it.
I would basically have to revert all changes made in `8f9d85a`.

I am however not entirely sure whether anything extra in the file structure will change.

**Comment by 1313e** [comment]
@telegraphic Could you rebase `dev` unto `master`, such that I can merge this into `dev`.
That way I can create separate PRs for separate additions/changes.

**Comment by telegraphic** [comment]
@1313e just merged

**Comment by 1313e** [comment]
I saw.
Thanks.

**Comment by 1313e** [comment]
So, if this could be merged into `dev`, then I can get started on the major refactor plan I have (for a version 4.0).

**Pull request merged**
