### PR TITLE
use dill if found

### PR DESCRIPTION
**Pull request by mmckerns**
Enable `hickle` to serialize most python objects seamlessly in the hdf files.  Probably better if one could pick the serializer at runtime, but this was easy.  No new dependency created, since it only uses `dill` if it's been installed.
```
>>> import hickle
>>> 
>>> f = open('foo.hkl', 'w')
>>> hickle.dump(lambda x:x, f)
dumping <type 'function'> to file <HDF5 file "foo.hkl" (mode r+)>
Warning: <type 'function'> type not understood, data have been serialized
>>> f.close()
>>> f = open('foo.hkl', 'r')
>>> g = hickle.load(f, safe=False)
>>> g(4)
4
```

### CODE REVIEW

**Comment by mmckerns** [comment]
Just a FYI, I think `hickle` could be very useful here: https://github.com/uqfoundation/klepto

**Comment by telegraphic** [comment]
Thanks, this is straightforward to merge. Re `klepto`: looks really neat! I'll have to check out `pathos` too. HDF5 sounds like a good choice for a data container for `klepto`, regardless of whether you used `hickle` or a focused custom implementation.

**Comment by mmckerns** [comment]
Functionality was removed (for what reason?) in #23.  The above provides easy solutions for open issues (#48, #39, etc).

**Comment by mmckerns** [comment]
Note that the current version of `hickle` requires some head-standing to store a class instance...

```
>>> import hickle as hkl
>>> class Foo(object):
...   pass
... 
>>> bar = Foo()
>>> hkl.dump(bar, 'test.hkl', 'w')
>>> a = hkl.load('test.hkl')
>>> a
array([ 'ccopy_reg\n_reconstructor\np1\n(c__main__\nFoo\np2\nc__builtin__\nobject\np3\nNtRp4\n.'], 
      dtype='|S76')
>>> import pickle
>>> a = pickle.loads(a.tostring())
>>> a
<__main__.Foo object at 0x103d169d0>
```

With `dill`, all you needed to do was:
```
>>> hkl.dump(bar, 'test.hkl', 'w')
>>> a = hkl.load('test.hkl')
>>> a
<__main__.Foo object at 0x103d169d0>
```

Which provides a much cleaner API, and (again) has much broader functionality.

**Pull request merged**
