### PR TITLE
Hickle v5.0.0

### PR DESCRIPTION
**Pull request by telegraphic**
We have merged @hernot's Hickle 5 rc branch into our dev-v5 branch, what else needs to be done before releasing v5.0.0?

### CODE REVIEW

**Comment by telegraphic** [comment]
Any reason to keep appveyor now we have github actions? (I think not?)

**Comment by 1313e** [comment]
> Any reason to keep appveyor now we have github actions? (I think not?)

No, that link should be removed at AppVeyor's side.

**Review by 1313e — APPROVED** [review]

**Comment by telegraphic** [comment]
@hernot and @1313e 🎉 :tada: :tada:

Thanks for your perserverance and patience!

**Comment by telegraphic** [comment]
I've updated the `PYPY_*` secrets so that the automated upload to pypi works.

The version is based on that in `__version__.py`, which created:
https://pypi.org/project/hickle/5.0.0.dev0/

We should change this to 5.0.0 once we're satisfied that it is working for end users

**Comment by hernot** [comment]
@telegraphic Cool thank you very much. 
By the way when officially releasd to pypi the issues #135, #139, #143 
And for #150 @1313e should suggest whether this should stay open as a reminder or can be closed.

**Pull request merged**
