### PR TITLE
make hickle work with pathlib.Path

### PR DESCRIPTION
**Pull request by basnijholt**
Basically, any package /module that saves to file supports this too (including `h5py`).

@tlaeven, this should also fix your problems ;)

### CODE REVIEW

**Comment by 1313e** [comment]
@basnijholt Supporting `Pathlib` should indeed be possible.
However, the changes you have made are not Python 2 compatible, as iterable unpacking cannot be done in tuples or lists in Python 2.
Can you change this?

**Comment by basnijholt** [comment]
@1313e, I have fixed it 👍

**Comment by basnijholt** [comment]
On an unrelated note, we should drop Python 2 support altogether 😄

**Comment by 1313e** [comment]
Thanks @basnijholt 

> On an unrelated note, we should drop Python 2 support altogether
That is for @telegraphic to decide.

**Comment by 1313e** [comment]
@telegraphic Do you want this in `dev` or `master`?
I think `master` is better, as it can be released immediately.

**Comment by basnijholt** [comment]
I consider it a bug fix, so hopefully, a patch release can be made :)

**Comment by 1313e** [comment]
> I consider it a bug fix, so hopefully, a patch release can be made :)

Exactly my thoughts.

**Comment by telegraphic** [comment]
Happy to merge direct into master. 

Re dropping Py2 support: I think there will be a clear time where maintaining Py2 will become burdensome, at which point I would be amenable to dropping it, but not ready to ditch it completely yet...

**Pull request merged**
