### PR TITLE
Last few changes

### LINKED ISSUE #90: Hickling NumPy arrays with dtypes that are not supported by h5py
I was just trying out `hickle` a bit and I am happy to see that it can easily hickle, for example, lists that contain multiple different types of objects (as that cannot be converted to a NumPy array and thus normally cannot be stored quickly by h5py).
However, I know that h5py will fail to save any NumPy array that has a non-supported dtype, of which some are quite far-fetched and some should simply be supported in the first place.
It seems that `hickle` does not support these either, which would be nice if they were added.

Examples of non-supported NumPy array dtypes (I know that there are more, but I cannot remember them as easily at the moment):
- `dtype('O')`, which are used by NumPy arrays if you give it anything that cannot be converted to a NumPy array (like dicts: `np.array({1: 2})` produces `array({1: 2}, dtype=object)`).
- `dtype('<UX')` with `X` being any integer, which are used by NumPy arrays holding unicode strings (Python 3 only probably). Saving any NumPy array of strings in Python 2 will work, as they are bytes strings.

The first example is obviously a bit far-fetched, as there is no reason to store a dict (or anything that cannot be converted to an array) in a NumPy array, but the second example is something that has its uses.

Also, I would like to mention that while the `hickle.load` function ensures that the opened HDF5-file is closed by using a `with`-statement (which, btw, makes the `try`-statement around it obsolete, unless the `finally`-clause will perform something else in the future), the `hickle.dump` function does not ensure this.
Therefore, when trying to hickle a NumPy array with one of the dtypes as described above, the HDF5-file will never be closed properly after raising the h5py error.

### LINKED ISSUE #130: 'track_times' argument for 'dump' has no use
So, while I was going through the tests of the package a bit for the v4 release, I noticed that the tests for the `track_times` optional argument do not actually do anything, which you can see here (if `caching_dump` is never called before the `test_track_times` function, which is the case, then that test does nothing as `DUMP_CACHE` is empty): https://github.com/telegraphic/hickle/blob/5e8f6260d476553da675e88ebecb2a7287341a8d/hickle/tests/test_hickle.py#L340-L374
That is actually a good thing, as it would infinitely loop in Python 3 due to string representation differences.

However, I decided to check what exactly `track_times` does.
According to the [`h5py` documentation](http://docs.h5py.org/en/stable/high/group.html?highlight=track_times#Group.create_dataset), this argument is solely used for creating datasets; is set to `True` by default; and enables the saving of the creation timestamps.
It is rather unclear actually what that means or what impact it has, and it is not mentioned anywhere else in the documentation.

But, seeing as it is set to `True` by default, which is the same default as `dump` has in `hickle`, there is no point in specifically asking for its value.
Furthermore, `dump` already allows for additional `kwargs` to be provided that are passed to the `create_dataset` method, so if anyone ever wants to set `track_times` to a different value, they can.

Also, in `hickle`, the argument is described as making sure that repeated hickling results in different files.
This description itself is very vague as what that exactly means, as repeated hickling using the exact same script either always results in a different file (if the file was opened for writing and truncated, thus becoming a new file) or impossible (if it was not truncated, causing the data to already exist with the same name).

Given the above, I feel like that the argument has no use besides confusing the user, and should therefore be removed in both v3 and v4.
@telegraphic What is your opinion?

### PR DESCRIPTION
**Pull request by 1313e**
Last few changes:
- Added all missing tests;
- NumPy arrays containing unicode strings can be properly dumped and loaded;
- NumPy arrays containing non-NumPy objects can be dealt with as well (fixes #90);
- Removed the use of 'track_times' (resolves #130);
- If an object fails to be hickled using normal means, `hickle` will now fall back to pickling the object;
- Massively simplified the way in which builtin Python scalars are stored.

### CODE REVIEW

**Comment by 1313e** [comment]
Alright, I think I am done now, unless you want me to look at #133.

**Comment by 1313e** [comment]
Oh, I think that the docs need to be rebuilt, but I don't know how to do that.

**Comment by 1313e** [comment]
Somehow I keep finding small things that I can improve real quick.
Please save me from this curse by releasing v4 as quickly as possible! :)

**Comment by telegraphic** [comment]
Merging!

**Pull request merged**
