### PR TITLE
properly save and retrieve a SkyCoord object when it's a scalar or N-D array

### PR DESCRIPTION
**Pull request by r-xue**
The current implementation always saves the SkyCoord object as an Nx2 array and doesn't work well if the coordinate value is a scalar or high-dimensional array

```python
In [2]: radec = SkyCoord(0, 0, unit='degree') 
   ...: hkl.dump(radec, "test_ap.h5") 
   ...: radec2 = hkl.load("test_ap.h5") 
   ...: print(radec,radec.isscalar) 
   ...: print(radec2,radec2.isscalar)                                                                                                                                           
<SkyCoord (ICRS): (ra, dec) in deg
    (0., 0.)> True
<SkyCoord (ICRS): (ra, dec) in deg
    [(0., 0.)]> False

In [3]: radec = SkyCoord(np.zeros((3,4)), np.zeros((3,4)), unit='degree') 
   ...: hkl.dump(radec, "test_ap.h5") 
   ...: radec2 = hkl.load("test_ap.h5") 
   ...: print(radec.shape) 
   ...: print(radec2.shape)                                                                                                                                                    
(3, 4)
(3,)
```

This PR is supposed to fix the issue. ``test_astropy.py`` is also slightly updated to reflect the change.

### CODE REVIEW

**Comment by 1313e** [comment]
Huh, surprising that I did not catch that `SkyCoord` has no `array` equivalent test, which would have caught this.
Nice catch!

Can you make a PR with the appropirate changes to the `v3` branch, and remove the changes you made to `legacy_v3` in this PR?
That way, we can fix this in both v3 and v4 (and you get credit for the fix in both versions).

**Comment by r-xue** [comment]
okay. it's done. hopefully, I get everything right.

**Comment by r-xue** [comment]
add another small change related to #37 (which shows up again in v4). the v3 branch seems to be fine. 
not relevant to the initial PR purpose, but let's get it covered here?

**Comment by 1313e** [comment]
@r-xue Thanks for that.
I finally have time again to do more important stuff, like this.

The last commit you added should be reverted, as it not only does not belong to this PR, but also because I very specifically reintroduced that change in v4.
Compression isn't the only thing `kwargs` can have.
A user would expect them to be passed along, so that's what I did.
As you normally cannot compress scalars in HDF5, I see no reason why the user would expect that to be a thing when using `hickle`.
And if HDF5 does allow compression on scalars in the future (doubtful, but possible), it would all of a sudden require an additional change in `hickle` to allow for that.

So, for that reason, I simply let `h5py` and HDF5 handle that error.
In case you are a bit uncomfortable with that: I did add something else to v4, where if any error is raised anywhere during dumping, it will dump the contents first using `pickle` and only reraise the error afterward.
You will therefore not lose your data due to attempting to store something incorrectly.

**Comment by r-xue** [comment]
yeah. I agree. keep consistency is important. Thank you for the excellent work.

**Pull request merged**
