### PR TITLE
Package license and requirements files

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by telegraphic** [comment]
Thanks!

**Comment by 1313e** [comment]
Can this also be instantly released, as currently `hickle` is not installable.

**Comment by telegraphic** [comment]
Have just pushed to PyPi, should fix #105

**Comment by 1313e** [comment]
I will actually make some changed in an hour and create a PR, that will test for these kinds of problems to avoid them in the future.

**Pull request merged**
